Add new CRTM version v2.4_jedi
JCSDA/spack pull request #156
Opened 2022-08-19 21:20 UTC by climbfuji

As the title says. See #https://github.com/NOAA-EMC/spack/issues/155 for a detailed description.

Fixes #155

2022-08-19 21:28 UTC, climbfuji commented
@BenjaminTJohnson FYI - please take a look and let me know what you think. Thanks!

2022-08-19 22:35 UTC, BenjaminTJohnson requested changes

2022-08-19 22:35 UTC, BenjaminTJohnson commented on var/spack/repos/builtin/packages/crtm/package.py
>      version("2.3.0", commit="99760e6")
Assuming these version values are tags or should be consistent with tags, this should be "v2.4.0_emc" and "v2.3.0_emc"

`v2.4.0_emc` tag has the commit: "5ddd0d6"
`v2.3.0_emc` tag has the commit: "99760e6"

`v2.3-jedi.4` is correct

`v2.4_jedi` should be "0ee3593"

Not sure why there's a discrepancy between internal and public repos on the commit hashes for the tags. I'll investigate, but for now, let's use what's on public only.

Let me know if I'm misunderstanding something.

2022-08-19 22:43 UTC, climbfuji commented
Thanks, you are right and I was wrong. Will make those changes.

> On Aug 19, 2022, at 4:35 PM, Benjamin Johnson ***@***.***> wrote:
> 
> 
> @BenjaminTJohnson requested changes on this pull request.
> 
> In var/spack/repos/builtin/packages/crtm/package.py <https://github.com/NOAA-EMC/spack/pull/156#discussion_r950592490>:
> 
> > @@ -41,5 +41,8 @@ class Crtm(CMakePackage):
>      version("2.4.0", commit="a831626")
>      # Uses the tip of REL-2.3.0_emc branch
>      version("2.3.0", commit="99760e6")
> Assuming these version values are tags or should be consistent with tags, this should be "v2.4.0_emc" and "v2.3.0_emc"
> 
> v2.4.0_emc tag has the commit: "5ddd0d6"
> v2.3.0_emc tag has the commit: "99760e6"
> 
> v2.3-jedi.4 is correct
> 
> v2.4_jedi should be "0ee3593"
> 
> Not sure why there's a discrepancy between internal and public repos on the commit hashes for the tags. I'll investigate, but for now, let's use what's on public only.
> 
> Let me know if I'm misunderstanding something.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/NOAA-EMC/spack/pull/156#pullrequestreview-1079402287>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB5C2RIBCNQ6IRXOTXEUCBLV2AD43ANCNFSM57B73CNQ>.
> You are receiving this because you authored the thread.
>

2022-08-22 15:52 UTC, srherbener approved these changes

2022-08-22 15:53 UTC, climbfuji commented
I am building all four versions of CRTM on my macOS now, and I found a bug or two - will update the PR in a bit.

2022-08-22 18:31 UTC, climbfuji commented
@srherbener @BenjaminTJohnson I was able to install all four versions of CRTM on my macOS after the latest bug fixes that I just pushed.

2022-08-23 02:20 UTC, climbfuji commented
Since @BenjaminTJohnson is on leave for three weeks and I used his corrected hashes, and since the PR was approved and everything built as expected, I am going to merge this once the unit tests passed.

2022-08-23 02:49 UTC, merged