Add scotch
JCSDA/spack pull request #260
Opened 2023-04-20 14:16 UTC by ulmononian

WW3 requires the `scotch` package for mesh/graph partitioning (see spack-stack [#465](https://github.com/NOAA-EMC/spack-stack/issues/465), [#336](https://github.com/NOAA-EMC/spack-stack/issues/336)).

This adds a checksum for `scotch/7.0.3` to the scotch package.py & adds `scotch` to the ufs-weather-model-env package.py.

Installs successfully as standalone package and as a part of ufs-weather-model-env (intel & gcc) on Orion.

2023-04-20 16:07 UTC, climbfuji reviewed
This all looks good, but we need to get the CI tests up and running again in your companion spack-stack PR. I'll work on that today/tomorrow.

2023-04-21 14:41 UTC, climbfuji requested changes
I'll mark this as "Request changes" because I am aware of segfaults on Hera that need to be figured out first. Otherwise, the PR looks good, installs cleanly in CI (macOS, Ubuntu), see https://github.com/NOAA-EMC/spack-stack/pull/550/files

2023-04-21 15:16 UTC, ulmononian commented
> I'll mark this as "Request changes" because I am aware of segfaults on Hera that need to be figured out first. Otherwise, the PR looks good, installs cleanly in CI (macOS, Ubuntu), see https://github.com/NOAA-EMC/spack-stack/pull/550/files

i believe the reported segfaults were using the hpc-stack version, so i need to try to build that slightly differently. i don't think anyone tested the spack-stack version of 7.0.3 within the context of ww3 yet, but hoping that goes more smoothly. will report back.

2023-04-25 15:25 UTC, climbfuji commented
> > I'll mark this as "Request changes" because I am aware of segfaults on Hera that need to be figured out first. Otherwise, the PR looks good, installs cleanly in CI (macOS, Ubuntu), see https://github.com/NOAA-EMC/spack-stack/pull/550/files
> 
> i believe the [reported segfaults ](https://github.com/NOAA-EMC/hpc-stack/issues/501#issuecomment-1516968295) were using the hpc-stack version, so i need to try to build that slightly differently. i don't think anyone tested the spack-stack version of 7.0.3 within the context of ww3 yet, but hoping that goes more smoothly. will report back.

Ok, please let me know when you had a chance to test it and I can approve/merge. Thanks!

2023-05-19 04:08 UTC, ulmononian commented
> I'll mark this as "Request changes" because I am aware of segfaults on Hera that need to be figured out first. Otherwise, the PR looks good, installs cleanly in CI (macOS, Ubuntu), see https://github.com/NOAA-EMC/spack-stack/pull/550/files

@climbfuji  i just merged develop into this. now it is just the scotch updates for spack that need to precede https://github.com/JCSDA/spack-stack/pull/550.

2023-05-19 16:07 UTC, climbfuji approved these changes

2023-05-19 16:07 UTC, merged