Feature/ufs utils pkgs
JCSDA/spack pull request #300
Opened 2023-08-10 21:15 UTC by HenryWinterbottom-NOAA

## Description

This PR updates the `ufs_utils/package.py` such that it complies with the stack required of the [UFS_UTILS](https://github.com/ufs-community/UFS_UTILS) applications. It is an extension of [#644](https://github.com/JCSDA/spack-stack/issues/644) and based on discussions with @climbfuji (see https://github.com/JCSDA/spack-stack/pull/645#pullrequestreview-1496061873).

## Issue(s) addressed

This is an extension of `spack-stack` issue [#644](https://github.com/JCSDA/spack-stack/issues/644).

## Dependencies

Spack-stack PR [#644](https://github.com/JCSDA/spack-stack/issues/644)

## Impact

This PR, in conjunction with [#644](https://github.com/JCSDA/spack-stack/issues/644), allows a stack to be compiled to support the `develop` branch of [UFS_UTILS](https://github.com/ufs-community/UFS_UTILS).

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

2023-08-16 22:44 UTC, climbfuji commented
@HenryWinterbottom-NOAA The style checks are failing due to a format change you made. Please revert - thanks.
```
==> Running black checks
--- var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py	2023-08-16 22:41:52.937568 +0000
+++ var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py	2023-08-16 22:42:12.521084 +0000
@@ -13,12 +13,11 @@
 
     homepage = "https://github.com/ufs-community/UFS_UTILS"
     git = "https://github.com/ufs-community/UFS_UTILS.git"
     # There is no URL since there is no code to download.
 
-    maintainers("AlexanderRichert-NOAA", "Hang-Lei-NOAA",
-                "HenryWinterbottom-NOAA")
+    maintainers("AlexanderRichert-NOAA", "Hang-Lei-NOAA", "HenryWinterbottom-NOAA")
 
     version("1.0.0")
 
     depends_on("bacio")
     depends_on("g2")
would reformat var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py
```

2023-08-16 22:44 UTC, climbfuji requested changes
Style checks fail.

2023-08-16 23:00 UTC, HenryWinterbottom-NOAA commented
> @HenryWinterbottom-NOAA The style checks are failing due to a format change you made. Please revert - thanks.
> 
> ```
> ==> Running black checks
> --- var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py	2023-08-16 22:41:52.937568 +0000
> +++ var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py	2023-08-16 22:42:12.521084 +0000
> @@ -13,12 +13,11 @@
>  
>      homepage = "https://github.com/ufs-community/UFS_UTILS"
>      git = "https://github.com/ufs-community/UFS_UTILS.git"
>      # There is no URL since there is no code to download.
>  
> -    maintainers("AlexanderRichert-NOAA", "Hang-Lei-NOAA",
> -                "HenryWinterbottom-NOAA")
> +    maintainers("AlexanderRichert-NOAA", "Hang-Lei-NOAA", "HenryWinterbottom-NOAA")
>  
>      version("1.0.0")
>  
>      depends_on("bacio")
>      depends_on("g2")
> would reformat var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py
> ```
@climbfuji I make the correction via `black`. Please let me know if the issue persists.

2023-08-16 23:34 UTC, climbfuji commented
> > @HenryWinterbottom-NOAA The style checks are failing due to a format change you made. Please revert - thanks.
> > ```
> > ==> Running black checks
> > --- var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py	2023-08-16 22:41:52.937568 +0000
> > +++ var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py	2023-08-16 22:42:12.521084 +0000
> > @@ -13,12 +13,11 @@
> >  
> >      homepage = "https://github.com/ufs-community/UFS_UTILS"
> >      git = "https://github.com/ufs-community/UFS_UTILS.git"
> >      # There is no URL since there is no code to download.
> >  
> > -    maintainers("AlexanderRichert-NOAA", "Hang-Lei-NOAA",
> > -                "HenryWinterbottom-NOAA")
> > +    maintainers("AlexanderRichert-NOAA", "Hang-Lei-NOAA", "HenryWinterbottom-NOAA")
> >  
> >      version("1.0.0")
> >  
> >      depends_on("bacio")
> >      depends_on("g2")
> > would reformat var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py
> > ```
> 
> @climbfuji I make the correction via `black`. Please let me know if the issue persists.

Thanks @HenryWinterbottom-NOAA - running the unit tests now. Sorry that this took so long to get to.

2023-08-16 23:35 UTC, HenryWinterbottom-NOAA commented
> > > @HenryWinterbottom-NOAA The style checks are failing due to a format change you made. Please revert - thanks.
> > > ```
> > > ==> Running black checks
> > > --- var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py	2023-08-16 22:41:52.937568 +0000
> > > +++ var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py	2023-08-16 22:42:12.521084 +0000
> > > @@ -13,12 +13,11 @@
> > >  
> > >      homepage = "https://github.com/ufs-community/UFS_UTILS"
> > >      git = "https://github.com/ufs-community/UFS_UTILS.git"
> > >      # There is no URL since there is no code to download.
> > >  
> > > -    maintainers("AlexanderRichert-NOAA", "Hang-Lei-NOAA",
> > > -                "HenryWinterbottom-NOAA")
> > > +    maintainers("AlexanderRichert-NOAA", "Hang-Lei-NOAA", "HenryWinterbottom-NOAA")
> > >  
> > >      version("1.0.0")
> > >  
> > >      depends_on("bacio")
> > >      depends_on("g2")
> > > would reformat var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py
> > > ```
> > 
> > 
> > @climbfuji I make the correction via `black`. Please let me know if the issue persists.
> 
> Thanks @HenryWinterbottom-NOAA - running the unit tests now. Sorry that this took so long to get to.

@climbfuji No need, at all, to apologize! Thank you for the opportunity to contribute and to learn something new!

2023-08-17 01:03 UTC, climbfuji approved these changes

2023-08-17 01:30 UTC, ulmononian commented
does netcdf-fortran need to be included twice?

2023-08-17 01:53 UTC, climbfuji requested changes

2023-08-17 01:53 UTC, climbfuji commented on var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py
> +    depends_on("netcdf-fortran")
Good catch @ulmononian I didn't see that.

2023-08-17 03:47 UTC, ulmononian approved these changes
looks good!!

2023-08-17 03:47 UTC, ulmononian commented on var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py
> +    depends_on("netcdf-fortran")
does netcdf-fortran need to be included twice?

2023-08-17 19:43 UTC, climbfuji commented on var/spack/repos/jcsda-emc-bundles/packages/ufs-utils-env/package.py
> +    depends_on("netcdf-fortran")
@HenryWinterbottom-NOAA Can you fix the double netcdf-fortran please?

2023-08-17 20:12 UTC, climbfuji approved these changes

2023-08-17 20:29 UTC, ulmononian approved these changes

2023-08-17 20:47 UTC, merged