Move meta-module creation into Spack extension
JCSDA/spack pull request #67
Opened 2022-05-20 23:00 UTC by kgerheiser

2022-05-23 13:11 UTC, climbfuji requested changes
This looks nice, will try out today. For the sake of consistency, what do you think of changing `spack stack env` to `spack stack environment` because we also spell it out for the meta modules and the containers?

2022-05-23 13:11 UTC, climbfuji commented on lib/jcsda-emc/spack-stack/stack/cmd/stack.py
> +    meta_modules_parser = sp.add_parser('setup-meta-modules', help='Create LMod meta-modules')
```suggestion
    meta_modules_parser = sp.add_parser('setup-meta-modules', help='Create lmod/lua or tcl/tk meta-modules')
```

2022-05-23 14:46 UTC, kgerheiser commented
Sure, we can make it `environment`. Just thought I would save a few letters.

2022-05-24 20:56 UTC, climbfuji commented
@kgerheiser Looks good. It's still a draft, please let me know when you think it's ready so that I don't miss it and you have to wait. Thanks!

2022-05-24 21:02 UTC, climbfuji approved these changes

2022-05-24 21:03 UTC, merged